### ISSUE TITLE
nginx reload & restart

### ISSUE THREAD

**Issue by Chreem** [pandasjw/blog#1]
[![image](https://cloud.githubusercontent.com/assets/12951147/23583924/f8d66e64-018c-11e7-9f21-1868f59bca5a.png)](http://pandasjw.com/2017/02/27/website-quick/)

According to [this answer](http://stackoverflow.com/questions/13525465/when-to-restart-and-not-reload-nginx), reload looks like better than restart.

> Reloading nginx is safer than restarting because before old process will be terminated, new configuration file is parsed and whole process is aborted if there are any problems with it.

---
Well, if not, please tell me why, 3cu.~~From a kid first uses issue function.~~

**Comment by pandasjw** [comment]
haha, I fixed this problem now. thanks☺

**Comment by pandasjw** [comment]
haha, I fixed this problem now. thanks！

**Comment by Chreem** [comment]
:P

**Comment by cheerzz** [comment]
yeah,here is two zz!
